### PR TITLE
Update filtering logic

### PR DESCRIPTION
**Pull request by JakobGray**
Story: https://github.com/open-cluster-management/backlog/issues/6754

### CODE REVIEW

**Comment by zkayyali812** [comment]
@JakobGray Maybe this is a negligible test, but have you tested this in the UI?

You wouldn't need to run console locally to run this test quickly

**Comment by JakobGray** [comment]
> @JakobGray Maybe this is a negligible test, but have you tested this in the UI?
> 
> You wouldn't need to run console locally to run this test quickly

No, I'll try that later today, and maybe demo tomorrow

**Pull request merged**
